name: brd4
channels:
  - conda-forge
dependencies:
  - python=3.11
  - rdkit=2024.09.4
  - pandas=2.2.3
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - ipykernel
  - chembl_webresource_client