name: brd4
channels:
  - conda-forge
dependencies:
  - python=3.11
  - rdkit=2024.09.4
  - pandas=2.2.3
  - numpy
  - scikit-learn
  - matplotlib
  - matplotlib-venn 
  - seaborn
  - tqdm
  - ipykernel
  - chembl_webresource_client
  - astartes
  - pytorch=2.6.0
  - torchmetrics
  - pyg
  - networkx
  - sympy